spring.application.name=BaiTap_26_9_2025
# C?u hình Spring Data JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true

spring.datasource.url=jdbc:sqlserver://DESKTOP-331CJKC:1433;databaseName=LTWEB_ST5_ST6;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.port=8093

spring.thymeleaf.cache=false
spring.messages.basename=i18n/messages

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql



